### ISSUE TITLE
Defintion for `pumit.tokenizer.SimpleVQTokenizer`

### ISSUE THREAD

**Issue by Masaaki-75** [function2-llx/PUMIT#5]
Hi! Thanks for open-sourcing; this work is fantastic!

I am trying to refactor the model to fit my own environment (unfortunately it contains other packages that require a lower torch/python version). I find that in `conf/tokenizer/simple/model.yaml` the tokenizer class `pumit.tokenizer.SimpleVQTokenizer` seems to be unavailable in the current version. Did I miss something?

**Comment by function2-llx** [comment]
Hi, thank you for your interest here. Our code on master branch is still under further development, so is might not be consistent, you should switch to the branch named `submit` to reproduce the results. After that, you can find the class at https://github.com/function2-llx/PUMIT/blob/submit/pumit/tokenizer/__init__.py#L4.
